language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t shajjad/docker-react -f Dockerfile.dev .
script:
  - docker run shajjad/docker-react npm run test -- --coverage